name       : haskell-psqueues
version    : 0.2.2.3
release    : 1
source     :
    - http://hackage.haskell.org/package/psqueues-0.2.2.3/psqueues-0.2.2.3.tar.gz : 6d757c30f6fdc8df7ed62601f2b2530e71192109ab94d06dec4176c9c3eea6b5
license    : BSD-3-Clause
component  : progrmming.haskell
summary    : The psqueues package provides Priority Search Queues in three different flavors. 
description: |
    The psqueues package provides Priority Search Queues in three different flavors. 
builddeps  :
    - haskell-cabal-install
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
