name       : haskell-psqueues
version    : 0.2.7.0
release    : 2
source     :
    - https://hackage.haskell.org/package/psqueues-0.2.7.0/psqueues-0.2.7.0.tar.gz : 4cf3628884015b091471e4425f5414207fd547cf71d9546e9b7318d857624fea
license    : BSD-3-Clause
component  : progrmming.haskell
summary    : The psqueues package provides Priority Search Queues in three different flavors.
description: "The psqueues package provides Priority Search Queues in three different flavors. \n"
builddeps  :
    - haskell-cabal-install
    - haskell-hashable
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
