name       : haskell-psqueues
version    : 0.2.7.2
release    : 3
source     :
    - https://hackage.haskell.org/package/psqueues-0.2.7.2/psqueues-0.2.7.2.tar.gz : 26263b555d943f9b18bbebda6a090848fdba3c1b403a9b7c848f6bac99e893f9
license    : BSD-3-Clause
component  : progrmming.haskell
summary    : The psqueues package provides Priority Search Queues in three different flavors.
description: |
    The psqueues package provides Priority Search Queues in three different flavors.
builddeps  :
    - haskell-cabal-install
    - haskell-hashable-devel
rundeps    :
    - devel:
        - haskell-hashable-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
